# Generated by Django 4.2 on 2023-04-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_name', models.CharField(choices=[('Dar', 'Dar es salaam')], max_length=255)),
                ('dictrict_name', models.CharField(choices=[('Ilala', 'Ilala')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landchange.address')),
            ],
        ),
        migrations.CreateModel(
            name='Landchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('photo', models.CharField(max_length=255)),
                ('comment_body', models.TextField()),
                ('remark', models.CharField(choices=[('Solved', 'Solved'), ('Not Solved', 'Not Solved')], max_length=255)),
                ('address_landchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landchange.address')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('admin_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='landchange.admin')),
                ('landchange_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='landchange.landchange')),
            ],
        ),
    ]
